replicaCount: 1
image:
  repository: mattjeanes/gptapi
  tag: latest
  pullPolicy: Always
ingress:
  host: ""
resources:
  requests:
    memory: "2Gi"
    cpu: "100m"
  limits:
    memory: "2Gi"
    cpu: "1500m"
env:
  normal:
    MODEL_FOLDER: /opt/gpt/models
    LENGTH: 50