apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gptapi
  name: gptapi
spec: 
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector: 
    matchLabels: 
      app: gptapi
  template: 
    metadata: 
      labels: 
        app: gptapi
        {{- if eq .Values.image.tag "latest" }}
        date: "{{ now | unixEpoch }}"
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec: 
      containers: 
      - image: {{ .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}
        name: gptapi
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        env:
        {{- range $key, $val := .Values.env.secret }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: gptapi
              key: {{ $key }}
        {{- end }}
        {{- range $key, $val := .Values.env.normal }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        volumeMounts:
        - name: gpt
          mountPath: /opt/gpt
        ports:
        - containerPort: 80
      volumes:
      - name: gpt
        azureFile:
          secretName: azure-storage-account
          shareName: gpt
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule